package my.awesome.plugin;

/******************************************************************/
/* Hi! Welcome to the generated source code of a PluginBlueprint! */
/*                                                                */
/* Just as a quick disclaimer:                                    */
/* If you're trying to get into *actual* programming, please      */
/* do NOT use this code as a starting point!                      */
/* This code was designed to be easily generated by more code     */
/* and goes against a whole lot of programming conventions in     */
/* terms of efficiency, readability & more.                       */
/*                                                                */
/* Anyway - have fun blueprinting and/or programming! :)          */
/* ~inventivetalent                                               */
/******************************************************************/
/****          Generated by PluginBlueprint                    ****/
/******************************************************************/
public class GeneratedPlugin extends org.bukkit.plugin.java.JavaPlugin implements org.bukkit.event.Listener {


/*** Start Fields ***/
private java.lang.String node_5_output_2;
private java.lang.String node_5_output_3;
private org.bukkit.plugin.PluginDescriptionFile node_5;
private org.bukkit.plugin.PluginDescriptionFile node_2_output_2;
private org.bukkit.plugin.java.JavaPlugin node_2;
private java.lang.String  node_6_output_1;
private java.lang.String  node_7_output_0 = "Enabling %s version %s!";
private java.lang.String  node_15_output_0 = "Hai";
private java.lang.String  node_16_output_0 = "Bai";
private java.lang.String  node_18_output_0 = "blub";
private java.lang.String[]  node_14_output_1;
private java.lang.Object[]  node_20_output_1;
private java.lang.String node_22_output_1;
/*** End Fields ***/



@java.lang.Override
public void onLoad() {
}

@java.lang.Override
public void onEnable() {
getServer().getPluginManager().registerEvents(this, this);

 node_2_exec();
 node_3_exec();
}

@java.lang.Override
public void onDisable() {
}

@java.lang.Override
public boolean onCommand(org.bukkit.command.CommandSender sender, org.bukkit.command.Command command, java.lang.String label, java.lang.String[] args) {
return true;
}


/*** Start Event Listeners ***/

/*** End Event Listeners ***/


/*** Start Object Methods ***/
// CLASS EXECUTION for PluginDescriptionFile
private void node_5_exec() {
java.lang.System.out.println("pb_debug_exec=5");/** Debug call **/
 node_5 =  node_2_output_2;
 node_5_output_2 =  node_5.getName();
 node_5_output_3 =  node_5.getVersion();
 node_6_exec();
}

// CLASS EXECUTION for JavaPlugin
private void node_2_exec() {
java.lang.System.out.println("pb_debug_exec=2");/** Debug call **/
  node_2 = this;
 node_2_output_2 =  node_2.getDescription();
}

/*** End Object Methods ***/


/*** Start Enum Methods ***/

/*** End Enum Methods ***/


/*** Start Generated Methods ***/

/*** End Generated Methods ***/


/*** Start Constructor Calls ***/

/*** End Constructor Calls ***/


/*** Start Method Calls ***/
// METHOD EXECUTION for org.bukkit.plugin.java.JavaPlugin#onEnable
private void node_3_exec() {
java.lang.System.out.println("pb_debug_exec=3");/** Debug call **/
 node_5_exec();
 node_14_exec();
}

// METHOD EXECUTION for java.util.Arrays#toString
private void node_22_exec() {
java.lang.System.out.println("pb_debug_exec=22");/** Debug call **/
 node_22_output_1 = java.util.Arrays.toString( node_20_output_1);
 node_17_exec();
}

/*** End Method Calls ***/


/*** Start Native Calls ***/
private void node_4_exec() {
java.lang.System.out.println("pb_debug_exec=4");/** Debug call **/
java.lang.System.out.println( node_6_output_1);
}

private void node_6_exec() {
java.lang.System.out.println("pb_debug_exec=6");/** Debug call **/
 node_6_output_1 = java.lang.String.format( node_7_output_0,  node_5_output_2, node_5_output_3);
node_4_exec();
}

private void node_14_exec() {
java.lang.System.out.println("pb_debug_exec=14");/** Debug call **/
 node_14_output_1 = new java.lang.String[] { node_15_output_0, node_16_output_0, node_18_output_0};
node_20_exec();
}

private void node_17_exec() {
java.lang.System.out.println("pb_debug_exec=17");/** Debug call **/
java.lang.System.out.println( node_22_output_1);
}

private void node_20_exec() {
java.lang.System.out.println("pb_debug_exec=20");/** Debug call **/
 node_20_output_1 = (java.lang.Object[])  node_14_output_1;
node_22_exec();
}

/*** End Native Calls ***/

}
